INSERT INTO genres (title) VALUES
('Hip-Hop'),
('Rap'),
('DrumNBass'),
('Trap'),
('Rock'),
('NY Drill'),
('Detroit'),
('UK Rap'),
('Emo Rap'),
('UK Drill');

INSERT INTO tracks (title, artist, genre_id, length)
VALUES
  ('Matt Hardy 999', 'Trippie Redd', 1, 188),
  ('i need u', 'Ken Carson', 2, 149),
  ('Undercover', 'Artificial Intelligence', 3, 357),
  ('Pop Out', 'KillBunk', 4, 180),
  ('America Fuck Yeah', 'Geek Music', 5, 163),
  ('Poland', 'Lil Yachty', 1, 83),
  ('OMG', 'Kankan', 4, 135),
  ('Out the way', 'Yeat', 4, 150),
  ('Sorry Bout That', 'Yeat', 4, 183),
  ('Off Tha Loot', 'Yeat', 1, 124),
  ('No Handoutz', 'Internet Money', 4, 150),
  ('Popa Yana', 'Clonnex', 4, 122),
  ('Poppin', 'Yeat', 4, 167),
  ('Rackz got me', 'Yeat', 1, 181),
  ('Taliban', 'Yeat', 4, 178),
  ('Still countin', 'Yeat', 4, 170),
  ('On Tha Line', 'Yeat', 4, 150),
  ('Doja', 'Central Cee', 8, 97),
  ('Riders on the Storm', 'Snoop Dogg', 2, 382),
  ('Rich Minion', 'Yeat', 4, 166),
  ('Cmon', 'Yeat', 4, 103),
  ('Get Busy', 'Yeat', 1, 158),
  ('Money so big', 'Yeat', 4, 160),
  ('Gummo', '6ix9ine', 4, 158),
  ('Rollin', 'Yeat', 4, 216),
  ('Antisocial 2', 'Tana', 1, 710),
  ('Antisocial', 'Tana', 4, 175),
  ('Wigga Wigga', 'Lil Morty', 4, 137),
  ('Body', 'Russ Millions', 10, 205),
  ('Industry Baby', 'Lil Nas X', 1, 212),
  ('Welcome To The Party', 'Pop Smoke', 6, 215),
  ('VIBEZ', 'DaBaby', 4, 145),
  ('Brawl Scum', 'grDAY', 7, 109),
  ('Awful Things', 'Lil Peep', 9, 214),
  ('For The Night', 'Pop Smoke', 4, 190),
  ('Traplanta', 'Lil Keed', 4, 166),
  ('Babushka Boy', 'Asap Rocky', 1, 187),
  ('Snake', 'Lil Keed', 4, 183),
  ('Lalala', 'bbnos', 4, 161),
  ('Traplanta', 'Lil Keed', 4, 166),
  ('6 For 6', 'Central Cee', 8, 149);